### ISSUE TITLE
数据库在哪里？

### ISSUE THREAD

**Issue by 35924784** [ANBUZHIDAO/wxmini-shop#1]
数据库在哪里？

**Comment by ANBUZHIDAO** [comment]
![image](https://user-images.githubusercontent.com/25934111/46958533-96ff0000-d0cc-11e8-9664-4122d2261a21.png)

在 conf\config.properties 文件里配置的。格式入文件所示。

我是申请了阿里云服务器上自己安装的MongoDB。
你需要自己配置自己的MongoDB数据库

**Comment by 35924784** [comment]
好的，多谢您。
